# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Location

# Model Form Field configuration
form: $/crazy/location/models/location/fields.yaml

# Model Class name
modelClass: Crazy\Location\Models\Location

# Default redirect location
defaultRedirect: crazy/location/locations

# Create page
create:
    title: backend::lang.form.create_title
    redirect: crazy/location/locations/update/:id
    redirectClose: crazy/location/locations

# Update page
update:
    title: backend::lang.form.update_title
    redirect: crazy/location/locations
    redirectClose: crazy/location/locations

# Preview page
preview:
    title: backend::lang.form.preview_title
